# Generated by Django 5.2.7 on 2025-11-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Ushtari',
        ),
    ]
