# Generated by Django 5.2.7 on 2025-11-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0002_rename_application_ushtari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ushtari',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ushtari',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ushtari',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='ushtari',
            name='message',
        ),
        migrations.AddField(
            model_name='ushtari',
            name='chapter_of_law',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='Neni i ligjit'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='date_of_act_epicrize',
            field=models.DateField(blank=True, null=True, verbose_name='Data e mandat arkëtimit (dd.mm.vvvv)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='date_of_act_physical_exam',
            field=models.DateField(blank=True, null=True, verbose_name='Data e vendimit (dd.mm.vvvv)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='date_of_law',
            field=models.DateField(blank=True, null=True, verbose_name='Data e ligjit (dd.mm.vvvv)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Datëlindja (dd.mm.vvvv)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='epicrize',
            field=models.CharField(default='-', max_length=130, verbose_name='Epikriza e identifikuar (Arti)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='family_name',
            field=models.CharField(default='-', max_length=50, verbose_name='Mbimri'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='father_name',
            field=models.CharField(default='-', max_length=50, verbose_name='Atësia'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='name',
            field=models.CharField(default='-', max_length=50, verbose_name='Emri'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Shënime'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='nr_act_epicrize',
            field=models.CharField(default='-', max_length=30, verbose_name='Nr. i mandatit'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='nr_act_physical_exam',
            field=models.CharField(default='-', max_length=30, verbose_name='Nr. i aktit'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='nr_of_law',
            field=models.CharField(default='-', max_length=30, verbose_name='Numri i ligjit'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='personal_id',
            field=models.CharField(default='-', max_length=30, verbose_name='Shenja personale'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='physical_exam',
            field=models.CharField(choices=[('afte', 'I aftë'), ('pa_afte', 'I paaftë'), ('blank', '-')], default='blank', max_length=10, verbose_name='Vlerësimi fizik'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='pob',
            field=models.CharField(default='-', max_length=120, verbose_name='Vendlindja'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='shdua_finish_date_1st',
            field=models.DateField(blank=True, null=True, verbose_name='Data e mbarimit SHDUA (dd.mm.vvvv)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='shdua_finish_date_2nd',
            field=models.DateField(blank=True, null=True, verbose_name='Data e mbarimit SHDUA (dd.mm.vvvv) (Rimobilizim 1)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='shdua_finish_date_3rd',
            field=models.DateField(blank=True, null=True, verbose_name='Data e mbarimit SHDUA (dd.mm.vvvv) (Rimobilizim 2)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='shdua_start_date_1st',
            field=models.DateField(blank=True, null=True, verbose_name='Data e fillimit SHDUA (dd.mm.vvvv)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='shdua_start_date_2nd',
            field=models.DateField(blank=True, null=True, verbose_name='Data e fillimit SHDUA (dd.mm.vvvv) (Rimobilizim 1)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='shdua_start_date_3rd',
            field=models.DateField(blank=True, null=True, verbose_name='Data e fillimit SHDUA (dd.mm.vvvv) (Rimobilizim 2)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='speciallity',
            field=models.CharField(default='-', max_length=30, verbose_name='Specialiteti (ESU)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='unit_nr_1st_time',
            field=models.CharField(default='-', max_length=30, verbose_name='RU numri, vendi'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='unit_nr_2nd_time',
            field=models.CharField(default='-', max_length=30, verbose_name='RU numri, vendi (Rimobilizim 1)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='unit_nr_3rd_time',
            field=models.CharField(default='-', max_length=30, verbose_name='RU numri, vendi (Rimobilizim 2)'),
        ),
    ]
