# Generated by Django 5.2.7 on 2025-11-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0003_remove_ushtari_created_at_remove_ushtari_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ushtari',
            name='id',
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='personal_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Shenja personale'),
        ),
    ]
