# Generated by Django 5.2.7 on 2025-11-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0004_remove_ushtari_id_alter_ushtari_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='speciallity',
            field=models.CharField(choices=[('KE', 'Këmbësori'), ('ART', 'Artileri'), ('LOGJ', 'Logjistikë'), ('NDER', 'Ndërlidhje')], default='blank', max_length=30, verbose_name='Specialiteti (ESU)'),
        ),
    ]
