# Generated by Django 5.2.7 on 2025-11-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0005_alter_ushtari_speciallity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='chapter_of_law',
            field=models.CharField(blank=True, default='----', max_length=30, null=True, verbose_name='Neni i ligjit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='epicrize',
            field=models.CharField(blank=True, default='----', max_length=130, null=True, verbose_name='Epikriza e identifikuar (Arti)'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='family_name',
            field=models.CharField(default='----', max_length=50, verbose_name='Mbimri'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='father_name',
            field=models.CharField(default='----', max_length=50, verbose_name='Atësia'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='name',
            field=models.CharField(default='----', max_length=50, verbose_name='Emri'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='nr_act_epicrize',
            field=models.CharField(blank=True, default='----', max_length=30, null=True, verbose_name='Nr. i mandatit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='nr_act_physical_exam',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='Nr. i aktit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='nr_of_law',
            field=models.CharField(blank=True, default='----', max_length=30, null=True, verbose_name='Numri i ligjit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='physical_exam',
            field=models.CharField(blank=True, choices=[('', '----'), ('afte', 'I aftë'), ('pa_afte', 'I paaftë')], default='----', max_length=10, null=True, verbose_name='Vlerësimi fizik'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='pob',
            field=models.CharField(choices=[('', '----'), ('A', 'Tropojë'), ('Ç', 'Malësi e Madhe'), ('D', 'Shkodër'), ('B', 'Kukës'), ('NJ', 'Has'), ('C', 'Pukë'), ('F', 'Mirditë'), ('O', 'Bulqizë'), ('G', 'Dibër'), ('H', 'Mat'), ('E', 'Lezhë'), ('K', 'Kurbin'), ('Q', 'Durrës'), ('I', 'Krujë'), ('U', 'Tiranë (qyteti)'), ('UU', 'Tiranë (rrethinat)'), ('Ll', 'Elbasan'), ('W', 'Lushnjë'), ('X', 'Kuçovë'), ('XH', 'Peqin'), ('SH', 'Librazhd'), ('P', 'Berat'), ('R', 'Gramsh'), ('RR', 'Pogradec'), ('N', 'Kolonjë'), ('S', 'Skrapar'), ('T', 'Korçë'), ('ZH', 'Fier'), ('Z', 'Vlorë'), ('Y', 'Mallakastër'), ('M', 'Tepelenë'), ('V', 'Sarandë'), ('TH', 'Gjirokastër')], default='----', max_length=30, verbose_name='Vendlindja'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='speciallity',
            field=models.CharField(blank=True, choices=[('0', '----'), ('1', 'Këmbësori'), ('2', 'Zbulim'), ('3', 'Mortaja 60, 82, 107, 120, 160 mm'), ('4', 'Artileri pa sbrapsje 75, 82, 107 mm'), ('5', 'Artileri 76, 85, 100, 122, 130, 122 obus, 152 mm top obuz'), ('6', 'Artileri reaktive 107, 130, 132 mm'), ('7', 'Artileri bregdetare 100, 130 mm TM 130 mm stac'), ('8', 'Raketë e drejturar kundër tanke'), ('9', 'Raketë e drejtuar kundërajrore'), ('10', 'Specialistë drejtimi të raketave'), ('12', 'Mitraloza kundërajorë 12.7, 14.5 mm'), ('13', 'Artileri kundërajrore 20, 25, 37, 57, 85, 100 mm'), ('14', 'Specialist të aparaturës së drejtimit të AKA-së'), ('15', 'Radiolokatore (p-8, p-10, p-11, e të tjerë), SDT dhe radiolokatorë të ndryshëm'), ('16', 'Zbulues të AKA-së'), ('17', 'Radiolokatorë për ABD'), ('18', 'Zbulues të artilerisë tokësore e bregdetare'), ('19', 'Topografë dhe topollogaritës'), ('20', 'Meteorologji'), ('21', 'Telementristë'), ('22', 'Projektoristë (specialist ndriçimi)'), ('23', 'Fotografi'), ('24', 'Teknik armatimi'), ('25', 'Teknik municioni'), ('26', 'Tanke dhe AVL'), ('27', 'Rregullues lëvizje'), ('28', 'Shoferë'), ('29', 'Motoçiklist'), ('30', 'Traktoristë, buldozerë, tërheqës'), ('31', 'Eskavatoristë'), ('32', 'Automekanikë'), ('33', 'Xhenerikë'), ('34', 'Axhustatorë'), ('35', 'Frezatorë'), ('36', 'Tornitorë'), ('37', 'Saldatorë, oksigjenistë'), ('38', 'Kovaç, llamarinistë'), ('39', 'Elektriçistë'), ('40', 'Elektroauto, akumulatoristë'), ('41', 'Motoristë'), ('42', 'Specialistë karburanti'), ('43', 'Xhenierë'), ('44', 'Muratorë'), ('45', 'Marangozë'), ('46', 'Kompresorë'), ('47', 'Hidraulikë'), ('48', 'Elektromagnetik'), ('49', 'Telefonistë-çentralistë'), ('50', 'Sinjalistë'), ('51', 'Radiofonistë, radiorelistë'), ('52', 'Radiotelegrafistë'), ('53', 'Telegrafistë'), ('54', 'Teknikë ndërlidhje'), ('55', 'Ekspeditor'), ('56', 'Mekanikë avioni helikopterë'), ('57', 'Mekanikë për armatimin e avionit'), ('58', 'Mekanikë për pajimet elektrike e radiopajimet'), ('59', 'Mekanikë për pajimet speciale të avionit dhe instrumentet'), ('60', 'Mekanikë për oksigjen'), ('61', 'Parashutistë'), ('62', 'Radiopelengatorë'), ('63', 'Teknikë për mjetet optike'), ('66', 'Kimi'), ('67', 'Flakëhedhës'), ('68', 'Sanitarë'), ('69', 'Shëndetësi'), ('70', 'Veterinari'), ('71', 'Laborantë'), ('72', 'Farmacistë'), ('73', 'Dentistë'), ('74', 'Nallbanë'), ('75', 'Këpucarë, berberë'), ('76', 'Rrobaqepës'), ('77', 'Shërbim prapavije'), ('78', 'Kuzhinierë, bukëpjekës, mullixhi'), ('79', 'Administratë'), ('80', 'Kompjutër (ordinator)'), ('81', 'Tipografistë'), ('82', 'Polici Ushtarake'), ('83', 'Muzikantë (fanarë)'), ('84', 'Këngëtarë, koristë, valltarë'), ('85', 'Përgjegjës kuverte'), ('86', 'Timonierë'), ('87', 'Elektroshturman'), ('88', 'Hidroakustikë'), ('89', 'Detar, minjor'), ('90', 'Siluristë'), ('91', 'Hidrografë'), ('92', 'Hamburistë'), ('93', 'radiometristë'), ('94', 'Kaldaistë'), ('95', 'Komando (forca speciale)'), ('96', 'Paqeruajtës'), ('97', 'Të pastërvitur'), ('98', 'Me veçori shërbimi')], default='', max_length=30, null=True, verbose_name='Specialiteti (ESU)'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='unit_nr_1st_time',
            field=models.CharField(blank=True, default='----', max_length=30, null=True, verbose_name='RU numri, vendi'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='unit_nr_2nd_time',
            field=models.CharField(blank=True, default='----', max_length=30, null=True, verbose_name='RU numri, vendi (Rimobilizim 1)'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='unit_nr_3rd_time',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='RU numri, vendi (Rimobilizim 2)'),
        ),
    ]
