# Generated by Django 5.2.7 on 2025-11-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0007_ushtari_perfunduar_alter_ushtari_physical_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ushtari',
            name='perfunduar',
        ),
        migrations.AddField(
            model_name='ushtari',
            name='shlyer_me_pagese',
            field=models.CharField(choices=[('----', '----'), ('Po', 'Po'), ('Jo', 'Jo')], default='Po', max_length=30, verbose_name='E ka shlyer me pagesë detyrin e SHDUA (po ose jo)?'),
        ),
    ]
