# Generated by Django 5.2.7 on 2025-11-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0008_remove_ushtari_perfunduar_ushtari_shlyer_me_pagese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='shlyer_me_pagese',
            field=models.CharField(choices=[('----', '----'), ('Po', 'Po'), ('Jo', 'Jo')], default='Po', max_length=30, verbose_name='A e ka shlyer me pagesë detyrin e SHDUA (po ose jo)?'),
        ),
    ]
