# Generated by Django 5.2.7 on 2025-11-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0010_alter_ushtari_shlyer_me_pagese'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ushtari',
            old_name='shdua_finish_date_1st',
            new_name='shdua_finish_date_1',
        ),
        migrations.RenameField(
            model_name='ushtari',
            old_name='shdua_finish_date_2nd',
            new_name='shdua_finish_date_2',
        ),
        migrations.RenameField(
            model_name='ushtari',
            old_name='shdua_finish_date_3rd',
            new_name='shdua_finish_date_3',
        ),
        migrations.RenameField(
            model_name='ushtari',
            old_name='shdua_start_date_1st',
            new_name='shdua_start_date_1',
        ),
        migrations.RenameField(
            model_name='ushtari',
            old_name='shdua_start_date_2nd',
            new_name='shdua_start_date_2',
        ),
        migrations.RenameField(
            model_name='ushtari',
            old_name='shdua_start_date_3rd',
            new_name='shdua_start_date_3',
        ),
    ]
