# Generated by Django 5.2.7 on 2025-11-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0011_rename_shdua_finish_date_1st_ushtari_shdua_finish_date_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ushtari',
            old_name='shlyer_me_pagese',
            new_name='paguar',
        ),
    ]
