# Generated by Django 5.2.7 on 2025-11-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0012_rename_shlyer_me_pagese_ushtari_paguar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='unit_nr_3rd_time',
            field=models.CharField(blank=True, default='----', max_length=30, null=True, verbose_name='RU numri, vendi (Rimobilizim 2)'),
        ),
    ]
