# Generated by Django 5.2.7 on 2025-11-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0013_alter_ushtari_unit_nr_3rd_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='nr_act_physical_exam',
            field=models.CharField(blank=True, default='----', max_length=30, null=True, verbose_name='Nr. i aktit'),
        ),
    ]
