# Generated by Django 5.2.7 on 2025-11-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0014_alter_ushtari_nr_act_physical_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titullari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funksioni', models.CharField(default='------ Funksioni -----', max_length=50)),
                ('grada', models.CharField(default='Gradë -----', max_length=50)),
                ('emri', models.CharField(default='Emër-----', max_length=50)),
                ('mbiemri', models.CharField(default='Mbiemër ---------- i atij që firmos -----', max_length=50)),
            ],
        ),
    ]
