# Generated by Django 5.2.7 on 2025-11-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0015_titullari'),
    ]

    operations = [
        migrations.AddField(
            model_name='titullari',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Titullari aktiv'),
        ),
        migrations.AlterField(
            model_name='titullari',
            name='emri',
            field=models.CharField(max_length=50, verbose_name='Emri'),
        ),
        migrations.AlterField(
            model_name='titullari',
            name='funksioni',
            field=models.CharField(max_length=50, verbose_name='Funksioni'),
        ),
        migrations.AlterField(
            model_name='titullari',
            name='grada',
            field=models.CharField(max_length=50, verbose_name='Grada'),
        ),
        migrations.AlterField(
            model_name='titullari',
            name='mbiemri',
            field=models.CharField(max_length=50, verbose_name='Mbiemri'),
        ),
    ]
