# Generated by Django 5.2.7 on 2025-11-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0016_titullari_is_active_alter_titullari_emri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='chapter_of_law',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Neni i ligjit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='epicrize',
            field=models.CharField(blank=True, default='', max_length=130, null=True, verbose_name='Epikriza e identifikuar (Arti)'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='family_name',
            field=models.CharField(default='', max_length=50, verbose_name='Mbimri'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='father_name',
            field=models.CharField(default='', max_length=50, verbose_name='Atësia'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Emri'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='nr_act_epicrize',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Nr. i mandatit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='nr_act_physical_exam',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Nr. i aktit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='nr_of_law',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Numri i ligjit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='pob',
            field=models.CharField(choices=[('----', '----'), ('A', 'Tropojë'), ('Ç', 'Malësi e Madhe'), ('D', 'Shkodër'), ('B', 'Kukës'), ('NJ', 'Has'), ('C', 'Pukë'), ('F', 'Mirditë'), ('O', 'Bulqizë'), ('G', 'Dibër'), ('H', 'Mat'), ('E', 'Lezhë'), ('K', 'Kurbin'), ('Q', 'Durrës'), ('I', 'Krujë'), ('U', 'Tiranë (qyteti)'), ('UU', 'Tiranë (rrethinat)'), ('Ll', 'Elbasan'), ('W', 'Lushnjë'), ('X', 'Kuçovë'), ('XH', 'Peqin'), ('SH', 'Librazhd'), ('P', 'Berat'), ('R', 'Gramsh'), ('RR', 'Pogradec'), ('N', 'Kolonjë'), ('S', 'Skrapar'), ('T', 'Korçë'), ('ZH', 'Fier'), ('Z', 'Vlorë'), ('Y', 'Mallakastër'), ('M', 'Tepelenë'), ('V', 'Sarandë'), ('TH', 'Gjirokastër')], default='', max_length=30, verbose_name='Vendlindja'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='unit_nr_1st_time',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='RU numri, vendi'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='unit_nr_2nd_time',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='RU numri, vendi (Rimobilizim 1)'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='unit_nr_3rd_time',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='RU numri, vendi (Rimobilizim 2)'),
        ),
    ]
