# Generated by Django 5.2.7 on 2025-11-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0017_alter_ushtari_chapter_of_law_alter_ushtari_epicrize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='date_of_act_epicrize',
            field=models.DateField(blank=True, null=True, verbose_name='Data e mandat arkëtimit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='date_of_act_physical_exam',
            field=models.DateField(blank=True, null=True, verbose_name='Data e vendimit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='date_of_law',
            field=models.DateField(blank=True, null=True, verbose_name='Data e ligjit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Datëlindja'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='shdua_finish_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='Data e mbarimit SHDUA'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='shdua_finish_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='Data e mbarimit SHDUA (Rimobilizim 1)'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='shdua_finish_date_3',
            field=models.DateField(blank=True, null=True, verbose_name='Data e mbarimit SHDUA (Rimobilizim 2)'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='shdua_start_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='Data e fillimit SHDUA'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='shdua_start_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='Data e fillimit SHDUA (Rimobilizim 1)'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='shdua_start_date_3',
            field=models.DateField(blank=True, null=True, verbose_name='Data e fillimit SHDUA (Rimobilizim 2)'),
        ),
    ]
