# Generated by Django 5.2.7 on 2025-11-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0018_alter_ushtari_date_of_act_epicrize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ushtari',
            name='paguar',
        ),
        migrations.RemoveField(
            model_name='ushtari',
            name='personal_id',
        ),
        migrations.AddField(
            model_name='ushtari',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Primary key (int)'),
        ),
        migrations.AddField(
            model_name='ushtari',
            name='personal_sign',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Shenja personale'),
        ),
    ]
