# Generated by Django 5.2.7 on 2025-11-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0019_remove_ushtari_paguar_remove_ushtari_personal_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ushtari',
            old_name='chapter_of_law',
            new_name='chapter_of_law_paguar',
        ),
        migrations.RenameField(
            model_name='ushtari',
            old_name='date_of_law',
            new_name='date_of_law_paguar',
        ),
        migrations.RenameField(
            model_name='ushtari',
            old_name='nr_act_epicrize',
            new_name='nr_act_paguar',
        ),
        migrations.RenameField(
            model_name='ushtari',
            old_name='nr_of_law',
            new_name='nr_of_law_paguar',
        ),
        migrations.RemoveField(
            model_name='ushtari',
            name='date_of_act_epicrize',
        ),
        migrations.AddField(
            model_name='ushtari',
            name='date_of_act_paguar',
            field=models.DateField(blank=True, null=True, verbose_name='Data e mandat arkëtimit të pagesës'),
        ),
    ]
