# Generated by Django 5.2.7 on 2025-11-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0020_rename_chapter_of_law_ushtari_chapter_of_law_paguar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='personal_sign',
            field=models.CharField(blank=True, choices=[('----', '----'), ('A', 'Tropojë'), ('Ç', 'Malësi e Madhe'), ('D', 'Shkodër'), ('B', 'Kukës'), ('NJ', 'Has'), ('C', 'Pukë'), ('F', 'Mirditë'), ('O', 'Bulqizë'), ('G', 'Dibër'), ('H', 'Mat'), ('E', 'Lezhë'), ('K', 'Kurbin'), ('Q', 'Durrës'), ('I', 'Krujë'), ('U', 'Tiranë (qyteti)'), ('UU', 'Tiranë (rrethinat)'), ('Ll', 'Elbasan'), ('W', 'Lushnjë'), ('X', 'Kuçovë'), ('XH', 'Peqin'), ('SH', 'Librazhd'), ('P', 'Berat'), ('R', 'Gramsh'), ('RR', 'Pogradec'), ('N', 'Kolonjë'), ('S', 'Skrapar'), ('T', 'Korçë'), ('ZH', 'Fier'), ('Z', 'Vlorë'), ('Y', 'Mallakastër'), ('M', 'Tepelenë'), ('V', 'Sarandë'), ('TH', 'Gjirokastër')], max_length=30, null=True, verbose_name='Shenja personale'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='pob',
            field=models.CharField(default='', max_length=30, verbose_name='Vendlindja'),
        ),
    ]
