# Generated by Django 5.2.7 on 2025-11-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0021_alter_ushtari_personal_sign_alter_ushtari_pob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='chapter_of_law_paguar',
            field=models.CharField(default='Neni 42', max_length=30, verbose_name='Neni i ligjit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='date_of_law_paguar',
            field=models.DateField(blank=True, default='10.07.2003', null=True, verbose_name='Data e ligjit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='nr_of_law_paguar',
            field=models.CharField(blank=True, default='9047', max_length=30, null=True, verbose_name='Numri i ligjit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='personal_sign',
            field=models.CharField(blank=True, choices=[('A', 'A- Tropojë'), ('Ç', 'Ç- Malësi e Madhe'), ('D', 'D- Shkodër'), ('B', 'B- Kukës'), ('NJ', 'NJ- Has'), ('C', 'C- Pukë'), ('F', 'F- Mirditë'), ('O', 'O- Bulqizë'), ('G', 'G- Dibër'), ('H', 'H- Mat'), ('E', 'E- Lezhë'), ('K', 'K- Kurbin'), ('Q', 'Q- Durrës'), ('I', 'I- Krujë'), ('U', 'U- Tiranë (qyteti)'), ('UU', 'UU- Tiranë (rrethinat)'), ('LL', 'LL- Elbasan'), ('W', 'W- Lushnjë'), ('X', 'X- Kuçovë'), ('XH', 'XH- Peqin'), ('SH', 'SH- Librazhd'), ('P', 'P- Berat'), ('R', 'R- Gramsh'), ('RR', 'RR- Pogradec'), ('N', 'N- Kolonjë'), ('S', 'S- Skrapar'), ('T', 'T- Korçë'), ('ZH', 'ZH- Fier'), ('Z', 'Z- Vlorë'), ('Y', 'Y- Mallakastër'), ('M', 'M- Tepelenë'), ('V', 'V- Sarandë'), ('TH', 'TH- Gjirokastër')], max_length=30, null=True, verbose_name='Shenja personale'),
        ),
    ]
