# Generated by Django 5.2.7 on 2025-11-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0022_alter_ushtari_chapter_of_law_paguar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='date_of_law_paguar',
            field=models.CharField(blank=True, default='10.07.2003', max_length=30, null=True, verbose_name='Data e ligjit'),
        ),
    ]
