# Generated by Django 5.2.7 on 2025-11-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0023_alter_ushtari_date_of_law_paguar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='chapter_of_law_paguar',
            field=models.CharField(blank=True, choices=[('42', '42')], default='', max_length=30, null=True, verbose_name='Neni i ligjit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='date_of_law_paguar',
            field=models.CharField(blank=True, choices=[('10.07.2003', '10.07.2003')], default='', max_length=30, null=True, verbose_name='Data e ligjit'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='nr_of_law_paguar',
            field=models.CharField(blank=True, choices=[('9047', '9047')], default='', max_length=30, null=True, verbose_name='Numri i ligjit'),
        ),
    ]
