# Generated by Django 5.2.7 on 2025-11-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0024_alter_ushtari_chapter_of_law_paguar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='date_of_act_paguar',
            field=models.DateField(blank=True, null=True, verbose_name='Data e mandatit të pagesës'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='nr_act_paguar',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Nr. i mandatit të pagesës'),
        ),
        migrations.AlterField(
            model_name='ushtari',
            name='personal_sign',
            field=models.CharField(blank=True, choices=[('A-', 'A- Tropojë'), ('Ç-', 'Ç- Malësi e Madhe'), ('D-', 'D- Shkodër'), ('B-', 'B- Kukës'), ('NJ-', 'NJ- Has'), ('C-', 'C- Pukë'), ('F-', 'F- Mirditë'), ('O-', 'O- Bulqizë'), ('G-', 'G- Dibër'), ('H-', 'H- Mat'), ('E-', 'E- Lezhë'), ('K-', 'K- Kurbin'), ('Q-', 'Q- Durrës'), ('I-', 'I- Krujë'), ('U-', 'U- Tiranë (qyteti)'), ('UU-', 'UU- Tiranë (rrethinat)'), ('LL-', 'LL- Elbasan'), ('W-', 'W- Lushnjë'), ('X-', 'X- Kuçovë'), ('XH-', 'XH- Peqin'), ('SH-', 'SH- Librazhd'), ('P-', 'P- Berat'), ('R-', 'R- Gramsh'), ('RR-', 'RR- Pogradec'), ('N-', 'N- Kolonjë'), ('S-', 'S- Skrapar'), ('T-', 'T- Korçë'), ('ZH-', 'ZH- Fier'), ('Z-', 'Z- Vlorë'), ('Y-', 'Y- Mallakastër'), ('M-', 'M- Tepelenë'), ('V-', 'V- Sarandë'), ('TH-', 'TH- Gjirokastër')], max_length=30, null=True, verbose_name='Shenja personale'),
        ),
    ]
