# Generated by Django 5.2.7 on 2025-11-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0027_alter_ushtari_personal_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='personal_sign',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Shenja personale'),
        ),
    ]
