# Generated by Django 5.2.7 on 2025-11-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0028_alter_ushtari_personal_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='physical_exam',
            field=models.CharField(blank=True, choices=[('afte', 'I aftë'), ('pa_afte', 'I paaftë')], default='----', max_length=10, null=True, verbose_name='Vlerësimi fizik'),
        ),
    ]
