# Generated by Django 5.2.7 on 2025-11-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0030_alter_ushtari_speciallity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='physical_exam',
            field=models.CharField(blank=True, choices=[('pa_afte', 'I paaftë')], default='----', max_length=10, null=True, verbose_name='Vlerësimi fizik'),
        ),
    ]
