# Generated by Django 5.2.7 on 2025-11-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0031_alter_ushtari_physical_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ushtari',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
