# Generated by Django 5.2.7 on 2025-11-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0032_ushtari_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
