# Generated by Django 5.2.7 on 2025-11-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0033_alter_ushtari_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hartoi', models.CharField(max_length=50, verbose_name='Konceptoi')),
                ('kontrolloi', models.CharField(max_length=50, verbose_name='Pranoi')),
                ('miratoi', models.CharField(max_length=50, verbose_name='Miratoi')),
            ],
        ),
    ]
