# Generated by Django 5.2.7 on 2025-11-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0034_firmat'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmat',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Firmëtarët aktiv'),
        ),
    ]
