# Generated by Django 5.2.7 on 2025-11-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shdua', '0036_alter_ushtari_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ushtari',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Datëlindja'),
        ),
    ]
